#!/bin/bash

function usage()
{
 cat << EOF

  Build and/or push images to Docker

  Syntax:
    build --image=<image you want to build>
          --from=<version of the parent image> 
          --tag=<tag for the image> 
          --repo=<docker repo by default "tofdocker"]
          [--clean]
          [--push]

  Values for image :
      - all
      - clang
      - swift4
      - vapor
      - vapor-mysql
      - vapor-postgresql
      - vapor-sqlite

EOF
  exit 255
}

function checkImage() {
  IMAGE=$1
   
  if [ "$IMAGE" == "all" ]
  then
    FROMS=( "" "" "" ":1.9" ":1.9" ":1.9" )
    TAGS=( ":1.6" ":1.0" ":1.9" ":1.9" ":1.9" ":1.9" )
    NAMES=( "clang" "swift4" "vapor" "vapor-mysql" "vapor-postgresql" "vapor-sqlite" )
  else
    NAMES+=( "$IMAGE" )
  fi
}

if [ "$#" -eq 0 ] 
then
  usage
else
  NAMES=()	
  FROMS=()
  TAGS=()
  DOCKERPUSH=0
  REPO="tofdocker/"

  for PARAM in "$@"
  do
		case $PARAM in
				--image=*)
          checkImage "${PARAM#*=}"
          shift
					;;
        --from=*)
          FROMS+=( "${PARAM#*=}" )
          shift
          ;;
        --tag=*)
          TAGS+=( "${PARAM#*=}" )
          shift
          ;;
        --repo=*)
          REPO="${PARAM#*=}/"
          shift
          ;;
        --clean)
          CLEAN="--no-cache=true"
          shift
          ;;
        --push)
          DOCKERPUSH=1
          shift
          ;;
				*)
          usage
				;;
		esac
  done
fi


DIR=$(pwd)

printf "\n\033[38;5;12mStart\033[0m\n\n"

for ((I=0;I<${#NAMES[@]};I++))
do
 cp install "${NAMES[$I]}/"
 printf "\033[38;5;12mBuild '${NAMES[$I]}' image\033[0m\n" 
 if [ "${NAMES[$I]}" == "vapor-mysql" ]
 then
  printf "\033[38;5;12mRemove volume: mysql.data\033[0m\n"
  docker volume rm mysql.data >& /dev/null
 fi
 if [ "${NAMES[$I]}" == "vapor-postgresql" ]
 then
  printf "\033[38;5;12mRemove volume: postgresql.data\033[0m\n"
  docker volume rm postgresql.data >& /dev/null
 fi
 docker build ${CLEAN} -t ${NAMES[$I]} ${NAMES[$I]}/
 if [ "$DOCKERPUSH" -eq 1 ] 
 then
  printf "\033[38;5;12mBuild '${REPO}${NAMES[$I]}${TAGS[$I]}' image\033[0m\n" 
  if [ ! -z "${FROMS[$I]}" ]
  then
    sed -i -e "s|FROM \([^ ]*\)|FROM ${REPO}\1${FROMS[$I]}|" ${NAMES[$I]}/Dockerfile  
    docker build -t ${REPO}${NAMES[$I]}${TAGS[$I]} ${NAMES[$I]}/
    sed -i -e "s|FROM ${REPO}\([^:]*\).*|FROM \1|" ${NAMES[$I]}/Dockerfile  
    rm ${NAMES[$I]}/Dockerfile-e
   else
    docker build -t ${REPO}${NAMES[$I]}${TAGS[$I]} ${NAMES[$I]}/
  fi
  docker push ${REPO}${NAMES[$I]}${TAGS[$I]}
 fi 
printf "\n\033[38;5;12m----------------------------------------------------\033[0m\n\n"
rm "${NAMES[$I]}/install"
done
printf "\n\033[38;5;12mFinished\033[0m\n\n"
