#!/bin/bash
function usage()
{
cat << EOF

  Refresh vapor packages

  Syntax:
    vapor-refresh-packages  --vapor=<environment name> [--clean]
            
  Values for environment:
      - alone 
      - mysql
      - postgresql
      - sqlite
      - all

EOF
exit 255
}

function project() 
{
  case $1 in
    alone)
      NAMES+=("vapor")
      PROJECTS+=("ItWorks")
      ;;
    mysql)
      NAMES+=("vapor-mysql")
      PROJECTS+=("ItWorks-MySQL")
      ;;
    postgresql)
      NAMES+=("vapor-postgresql")
      PROJECTS+=("ItWorks-PostgreSQL")
      ;;
    sqlite)
      NAMES+=("vapor-sqlite")
      PROJECTS+=("ItWorks-Sqlite")
      ;;
    all)
      NAMES=( "vapor" "vapor-mysql" "vapor-postgresql" "vapor-sqlite" )
      PROJECTS=( "ItWorks" "ItWorks-MySQL" "ItWorks-PostgreSQL" "ItWorks-Sqlite" )
      ;;
  esac
}

if [ "$#" -eq 0 ] 
then
  usage
else
  NAMES=()
  PROJECTS=()
  CLEAN=false
  for PARAM in "$@"
  do
    case $PARAM in
        --vapor=*)
          project "${PARAM#*=}"
          shift
          ;;
        --clean)
          CLEAN=true
          shift
          ;;
        *)
          usage
          ;;
    esac
  done
fi

if [ ${#NAMES[@]} -gt 0 ]
then
  DIR=$(pwd)

  for ((I=0;I<${#NAMES[@]};I++))
  do
   #clear
   printf "\n\033[38;5;12mRefresh packages for '${NAMES[$I]}' \033[0m\n\n"
   
   if [ $CLEAN == true ]
   then
     printf "\033[38;5;33mForce clean and prefetch project\033[0m\n"
     CMD="cd ${PROJECTS[$I]} && echo Current folder: \$PWD ; rm -rf .build/ ; rm Packages.resolved ; swift package update"
     docker run -ti --rm --name ${NAMES[$I]} -v $DIR/${NAMES[$I]}/projects/:/vapor ${NAMES[$I]} /bin/bash -c "$CMD"
     printf "\n"
   fi 

   printf "\033[38;5;33mUpdate project\033[0m\n"
   CMD="cd ${PROJECTS[$I]} && echo Current folder: \$PWD ; vapor update"
   docker run -ti --rm --name ${NAMES[$I]} -v $DIR/${NAMES[$I]}/projects/:/vapor ${NAMES[$I]} /bin/bash -c "$CMD"
     
   printf "\n\033[38;5;33mBuild project\033[0m\n"
   CMD="cd ${PROJECTS[$I]} && echo Current folder: \$PWD ; vapor build"
   docker run -ti --rm --name ${NAMES[$I]} -v $DIR/${NAMES[$I]}/projects/:/vapor ${NAMES[$I]} /bin/bash -c "$CMD"
  done
fi
